---
- name: show return value of apt module
  hosts: server1
  gather_facts: False
  sudo: True
  tasks:
    - name: install nginx
      apt: name=nginx
      register: result
    - debug: var=result
